crs: "EPSG:4326"
aoi:
    county_fips: "06037" # Los Angeles County
    bbox: [-118.74, 33.64, -117.74, 34.64]
sources:
    cooling:
        url: "https://services.arcgis.com/RmCCgQtiZLDCtblq/ArcGIS/rest/services/Cooling_Centers_-_Los_Angeles_County_Regional_(Official_-_Updated_July_2022)_(View)/FeatureServer/0/query"
    calheatscore:
        base_url: "https://data.ladwp.com/datasets/public/electric/calheatscore.csv"
        api_key: "YOUR_API_KEY"
paths:
    processed: "data/processed"
score:
    weights:
        heat: 0.34
        svi: 0.33
        resource_gap: 0.33
        